theme: jekyll-theme-dinky
show_downloads: true
github:
  zip_url: https://github.com/JD2112/ImageProcessingMATLAB/archive/refs/tags/v1.0.zip
  tar_url: https://github.com/JD2112/ImageProcessingMATLAB/archive/refs/tags/v1.0.tar.gz
